#!/bin/sh
echo
echo "Doing DKMS steps"
echo
VER=2.1.80
dkms add -m agrsm-11c11040 -v $VER
dkms build -m agrsm-11c11040 -v $VER
dkms install -m agrsm-11c11040 -v $VER
echo
echo "Finding installed modules:"
find /lib/modules/`uname -r` -name agr*.ko
echo
echo "Done"
echo



